### ISSUE TITLE
"no-curly" rule ?

### ISSUE THREAD

**Issue by nicolashenry** [ajafff/tslint-consistent-codestyle#14]
I noticed a "no-curly" rule in tslint-consistent-codestyle 1.2.0 module installed from npm which does not exist on this repository : 

![image](https://cloud.githubusercontent.com/assets/139160/25950888/4fb2aa82-365c-11e7-91bf-f3ce4a871bc3.png)

**Comment by ajafff** [comment]
Yeah, that rule is currently under development and slipped into the published package. 

Does it cause problems for you or is this issue just out of curiosity? 

You can expect it to be officially released and documented in the next version of the package.

**Comment by nicolashenry** [comment]
I was using this tool https://www.npmjs.com/package/check-tslint-all and the only rule I didn't put in my tslint.json file was this one. This is not really an issue but it took me a while to understand where does it come from.

**Comment by ajafff** [comment]
`no-curly` has been renamed and published as `ext-curly` with tslint-consistent-codestyle@1.4.0
