### ISSUE TITLE
Error when running rules recursively over directory

### ISSUE THREAD

**Issue by mikevanoo-fsg** [ajafff/tslint-consistent-codestyle#15]
Using tslint 5.2.0 and tslint-consistency-codestyle 1.2.0 and the attached tslint.json file (which uses just the example "naming-convention" rule found here: https://www.npmjs.com/package/tslint-consistent-codestyle).

Running the following:
`tslint -c tslint.json 'src/**/*.ts'`

Generates this error:

![error](https://cloud.githubusercontent.com/assets/28651355/25998908/fe7b9498-371a-11e7-91e5-5f271e3b85be.png)

Am I missing some arguments?

[tslint.json.txt](https://github.com/ajafff/tslint-consistent-codestyle/files/996132/tslint.json.txt)

**Comment by ajafff** [comment]
I guess your globally installed version of tslint does not match your locally installed version of tslint-consistent-codestyle

You can either try `node_modules\.bin\tslint -c tslint.json 'src/**/*.ts'` or update your global tslint with `npm update tslint typescript -g`

**Comment by mikevanoo-fsg** [comment]
Bingo!
`npm update tslint typescript -g`
did the trick.

Thank you.
