### ISSUE TITLE
An option to always do early-return 

### ISSUE THREAD

**Issue by michaeljota** [ajafff/tslint-consistent-codestyle#25]
I was wondering if you can add an option to always do early return. Thanks you.

**Comment by ajafff** [comment]
@michaeljota Can you provide some examples of what "always do early return" means for you?

**Comment by michaeljota** [comment]
There is a `early-exit`, with the following config object schema `"early-exit": [true, { "max-length": 4 }}`. I would like an option like `"always": true`, meaning I guess like `max-length": 0`.

**Comment by ajafff** [comment]
I got that. I'd like to see some code examples that show what you want this option to do. That means code that passes with the option enabled and code that does not pass.

**Comment by ajafff** [comment]
Sorry for the delay. I'll look into this. Should be part of the next release.
