### ISSUE TITLE
Error in dependencies tsutils

### ISSUE THREAD

**Issue by wKoza** [ajafff/tslint-consistent-codestyle#35]
Hi,

We have an error when we install tslint-consistent-codestyle v1.7. The dependency tsutils 2.11.0 doesn't exist.

Can you patch your package.json ?

**Comment by ajafff** [comment]
> ajaff published 4 hours ago
> 2.11.0 is the latest of 31 releases

That version exists on npm.
Do you use a proxy for accessing the npm registry? Maybe it's a caching problem

**Comment by wKoza** [comment]
Hey , our Nexus is strange today...
Sorry !
