### ISSUE TITLE
no-unused: callback arguments

### ISSUE THREAD

**Issue by dvlsg** [ajafff/tslint-consistent-codestyle#39]
Question for you (maybe a bug?) regarding `no-unused` and callback args. If I need to use a callback arg which is somewhere towards the right side of the list of args, but I don't need to use some of the preceding args, should that be an error?

Here's a screenshot of some code I'm working with, using `rewriters` in [winston 2.x](https://github.com/winstonjs/winston/tree/2.x#filters-and-rewriters).

![image](https://user-images.githubusercontent.com/4721566/33350037-aecca8fe-d451-11e7-9f0d-9d7d8e69c77e.png)

I don't think I can use placeholders to ignore elements like we could with array destructuring.

**Comment by ajafff** [comment]
You can either prefix the parameter name with an underscore, e.g. `_level`, or use the `"ignore-parameters"` option

**Comment by dvlsg** [comment]
Ahh I [see it](https://github.com/ajafff/tslint-consistent-codestyle/blob/master/docs/no-unused.md#ignore-parameters). Works for me -- thanks for taking the time to point me in the right direction, I appreciate it.
