### ISSUE TITLE
naming-convention camelCase for variables vs real world

### ISSUE THREAD

**Issue by morriq** [ajafff/tslint-consistent-codestyle#40]
Hello,

first of all - thanks for great linter.

I have such variables in my code:
articleID,
addUIPart,
isCKELoaded

and so on,
I would like to keep this rule on but with some excludes, is it possible?

same with methods

**Comment by ajafff** [comment]
Currently it's only possible to completely disable the format check for certain names.
I think it makes sense to add new format options for loose camel/pascal/snake/upper case.
I'm not sure if I want to make the loose check the default (restoring the behavior of v0.x) and add options like `"strictCamelCase"`. Or if it makes more sense the other way around: strict by default with an additional option to loosen the that behavior.

**Comment by morriq** [comment]
`strictCamelCase` on `false` will stop informing about lint errors?
I can suggest something like `whitelist` in `format` object. Define there regexps/vars which should be ignored.

`{format: "camelCase", whitelits: ["id", "ui", "cke"]}`

**Comment by ajafff** [comment]
IMO that whitelist idea is a bit too specific. If you want to enforce such naming conventions, you probably want to use a regexp pattern.

I'm thinking about something like the following:
`{"format": "strictCamelCase"}` requires names like `articleId`, `addUiPart`, ... the same as it works now.
`{"format": "camelCase"}` allows `articleID`, `addUIPart`, ... while still disallowing PascalCase (`ArticleID`) and underscores -> this is what you want for your use case

**Comment by morriq** [comment]
Sounds good to me :) 👍

**Comment by ajafff** [comment]
This change was just released as part of v1.11.0
