### ISSUE TITLE
early-exit: add option for disabling in constructors

### ISSUE THREAD

**Issue by jesperzach** [ajafff/tslint-consistent-codestyle#48]
To me, it feels unconventional to use return in a constructor and it can potentially override the object reference if a non-primitive type is returned. I like the `early-exit` rule, but would love be able to enable an option that would disable the rule inside all constructors.

**Comment by ajafff** [comment]
Agreed. Adding a new option sounds reasonable.

**Comment by cheeZery** [comment]
I'd like to take a swing at this.
