### ISSUE TITLE
no-unnecessary-type-annotation – infinite loop

### ISSUE THREAD

**Issue by johnsoft** [ajafff/tslint-consistent-codestyle#57]
Sorry in advance for what might be an unhelpful report. I somehow wrote some code that causes the `no-unnecessary-type-annotation` rule to get stuck in an infinite loop inside `removeSignatureReturn`. It is getting passed the string `'<A extends Action>(action: A): A'`, which appears to come from the [redux type definitions](https://github.com/reactjs/redux/blob/v3.7.2/index.d.ts#L108). The function seems to assume the first char will be `(`, but in my case it is `<`. Fixing that localized issue is easy, but I have no idea what broader conditions caused that to happen, or how you'd write a test for it.

**Comment by ajafff** [comment]
Thank you for this report and useful hint how to reproduce the issue.
This is fixed in v1.12.2
