### ISSUE TITLE
naming-convention

### ISSUE THREAD

**Issue by tonysamperi** [ajafff/tslint-consistent-codestyle#86]
If I use the following rule

<pre><code>{
  "type": "variable",
  "modifiers": [
    "export",
    "const"
  ],
  "format": "camelCase"
}</code></pre>

everything is fine.
But if I use 

<pre><code>{
  "type": "variable",
  "modifiers": [
    "export",
    "const"
  ],
  "format": "camelCase",
  "prefix": "some"
}</code></pre>

it triggers a false error on "camelCase"

**Comment by ajafff** [comment]
That's kind of expected. The documentation states that format checks are done after removing prefix and suffix. That means you need to use `"format": "PascalCase"` when using `prefix`.

**Comment by tonysamperi** [comment]
Actually..I didn't think about that.

You're totally right. Thanks a lot!
