### ISSUE TITLE
naming-convention throws an exception on latest TS versions

### ISSUE THREAD

**Issue by wh1t3cAt1k** [ajafff/tslint-consistent-codestyle#96]
When running a linter on the latest (3.1.2) typescript version I cannot use the naming-convention rule due to an enormous number of errors: `ts.unescapeIdentifier is not a function`

Perhaps it was deprecated and the rule should be rewritten without its usage?

There was also another rule with the same error (prefer-const-enum, I believe).

**Comment by wh1t3cAt1k** [comment]
I believe it is due to the `tsutils` dependency:
https://github.com/SonarSource/SonarTS/issues/668

**Comment by ajafff** [comment]
This was fixed in tsutils. Do you use the latest version of that package (somewhere around 2.26.x)? Maybe your lockfile needs to be updated
